# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94dcf5cbf1ef7109fd0101491577016c5962c42f3a1bf727848858f002c1362ca2155ac50a9306a05792fe7a45c2720de71e5682256965c605c6ad8225cdd750

test:
  secret_key_base: 8cd5fb39449b3c6ed34a07702caac510272f556e16e90e6b8c06a5d269c520e526ef1e23d8ddff2e53c18870311f5dfc7f8955661bd9fd05a0c938c7f21c6da8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
